### ISSUE TITLE
OAI dateIssued in oai_adl sometimes fails to map to [text string field].

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#100]
# Summary

Data in the "record/metadata/mods/originInfo/dateIssued" XML path sometimes fails to map to `date_issued`.  (From https://docs.google.com/document/d/1LmGsLw95CqBmRkRk5WJPYi2Y9KIZpktaO2ac3-1sl8o/edit)

With changes from #152 we should verify the acceptance criteria as it may be resolved via !209.
# Acceptance Criteria

- [ ] Given this [OAI URL](http://oai.adventistdigitallibrary.org/OAI-script?verb=GetRecord&metadataPrefix=mods&identifier=22252386) when I ingest that work then it's `date_issued` field should include "1927-12-15"

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

- [3]DC term metadata mapping
- Revisit Parser Mappings with 2022-10-27 Information and Later

**Comment by DiemBTran** [comment]
Related MRs:

- [Updated shared parser mappings](https://gitlab.com/notch8/adventist-dl/-/merge_requests/209)

**Comment by KatharineV** [comment]
Just an FYI on why this ticket is waiting in this column: 
I can't test this ticket on staging or production until we resolve the overall problems importing the adl:issue set via Bulkrax. I need to run a new, clean adl:issue import to generate up-to-date works for testing.

**Comment by KatharineV** [comment]
Issues imported today are not showing dateIssued, but it is because of a bigger problem here. The dateIssued field in MODS is not mapping to OAI_ADL for the first 100 works in the adl:issue set. 

See this example in [MODS](http://oai.adventistdigitallibrary.org/OAI-script?verb=GetRecord&metadataPrefix=mods&identifier=20088829), [OAI_ADL](http://oai.adventistdigitallibrary.org/OAI-script?verb=GetRecord&metadataPrefix=oai_adl&identifier=20088829), and on [Hyku](https://adl.s2.adventistdigitallibrary.org/concern/published_works/20088829_atlantic_union_gleaner_april_8_1903?locale=en). 

In that example, you will see that dateIssued metadata is present in MODS but doesn't map to OAI_ADL, and this is why it is missing from Hyku. 

Can you help me fix this? I no longer have support from Eric Koester, who originally worked on these mappings from our end. If I can fix the MODS to OAI_ADL mapping, then I will be able to properly test this ticket.

**Comment by jeremyf** [comment]
@KatharineV I'm following up with the team to see what the best approach would be.

At present I have two initial ideas:

1. We look at the code that Eric wrote to see about amending this record; I'm uncertain about the entire ecosystem for deploying changes.
2. We pivot to use the MODS feed, which would involve starting over with a modified approach for the OAI importer.  This one is not without risk, given that we've been testing against OAI ADL.

I'll try to get a few recommendations around this week.

**Comment by KatharineV** [comment]
@jeremyf thanks for all this info. I agree with the recommendation you share in the pros & cons document. I think we should create a report, attempt to fix manually, and then move to the script option to fetch date metadata from MODs. I expect that we will need the script in the end. I expect the number of works with missing date data to be high. As a side note, I checked the oai_dc metadata for the sample record referenced at the top of this ticket. The oai_dc is also missing the date_Issued metadata. For some reason, the date data deadends at MODs. So, all this to say that your recommendation looks better and better the longer I dig into the problem. Thanks.

**Comment by jeremyf** [comment]
I think based on this feedback, we should close this ticket as the next steps don't trick to the original ticket.

Also, since the plan is for you export a CSV, that would be an opportunity to amend the data when you then reimport the metadata.
