### ISSUE TITLE
[3]DC term metadata mapping

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#113]
# Summary
Overarching Goal: The CSV metadata mappings map to Qualified Dublin Core headings

The librarians are more familiar with the Qualified Dublin Core headings, so Adventist would like the metadata mappings to be mapped to those.

Qualified Dublin Core Headings (column E): https://docs.google.com/spreadsheets/d/1GEsyaFNias1JmnAkRLZbMYsBIaV-1rxl/edit#gid=1720793301 

# Acceptance Criteria

- [ ] A CSV with Qualified Dublin Core headings specified in the mapping document can be imported into the system

# Screenshots or Video

# Testing Instructions

- With the example (https://drive.google.com/file/d/1n3LFmo1DdOHXq3PSqK145ThN-b2Zt3GN/view?usp=sharing)  look at one of the works and identify what data you expect.  Review the mappings in config/initializers/bulkrax.rb to see what fields they will likely show up in.
- Create an importer that will use the CSV parser.
- Load that CSV and run the importer
- Review the record

**_Note_**: One challenge with this for client QA is that we have additional work to consider for the field mappings.  These are identified/tracked in #196.  Before we send this forward to the client for QA, we need to work on #196.

**Comment by DiemBTran** [comment]
Linked items:

Blocks:
- [5] Fix OAI QDC import

Relates to:
- Epic: CSV Importer that accepts DC
- Revisit Parser Mappings with 2022-10-27 Information and Later
- OAI Import `physicalDescription` in `MODS` isn’t mapping to extent
- OAI dateIssued in MODS sometimes fails to map to [text string field].
- OAI relatedItem/titleInfo/title not mapping to partOf/Series in a Published Work
- OAI originInfo/edition not mapping to Edition in published works
- Abstract is not mapping to abstract for generic work and image
- Incorrect metadata somehow populates the “partOf” field in Hyku and

**Comment by DiemBTran** [comment]
Related MRs:

- [Enabling the CSV Parser](https://gitlab.com/notch8/adventist-dl/-/merge_requests/202)
!202
- [updated csv mappings to QDC headings](https://gitlab.com/notch8/adventist-dl/-/merge_requests/204)
!204
- [Updated shared parser mappings](https://gitlab.com/notch8/adventist-dl/-/merge_requests/209)
!209

**Comment by DiemBTran** [comment]
Alisha Nov 2022:

---

@DeonFranklin I'm trying to qa this ticket but I'm not sure what the required fields shown below should be. can you fill me in?



![Image](https://user-images.githubusercontent.com/29311858/200630531-66fe6a8d-8851-4747-8f38-16a4a49ce463.png)

---

Alisha Nov 2022:

---

diem noticed the same behavior whil qa'ing another ticket. per the [slack conversation](https://assaydepot.slack.com/archives/G0311DN2YCA/p1667866283501679), this should not be. jeremy stated that the fix is most likely in `main` but not pushed to staging yet. 

labeling this ticket as blocked until the parser fields for csv are corrected.

**Comment by jeremyf** [comment]
@DiemBTran  I have deployed the changes to staging and dev.  What that means is we want to test the CSV parser.  And there won't be any prompts for `Base url` nor `set` nor `Metadata prefix`.  I hope this gets you unstuck.

**Comment by KatharineV** [comment]
I ran two CSV importer tests on staging, and here is what I see regarding the metadata mapping. 

Test one: https://adl.s2.adventistdigitallibrary.org/importers/45?locale=en I left the identifier.ark column heading.

Test two: https://adl.s2.adventistdigitallibrary.org/importers/46?locale=en I removed the .ark from the identifier.ark column, because this was required to keep the importer from reporting an error.

METADATA ISSUES

- Test one populated the AARK Identifier field in the finished works, which is desired behavior. [Example](https://adl.s2.adventistdigitallibrary.org/concern/generic_works/p007205_herd_of_yaks_1930s?locale=en).
- Test two did not populate the AARK Identifier field, which we need. Also, as a result, the URLs did not become human-readable. This is undesirable behavior. [Example](https://adl.s2.adventistdigitallibrary.org/concern/generic_works/d6b2f11b-40ca-42f4-a5a6-e3e3a4a41134?locale=en).
- Both tests failed to map relation.isPartOf to partOf, although there was metadata in a field with that title.
- Both tests failed to map format.extent to extent, however, the problem here is that the CSV parser created Generic Works rather than Image Works, so the extent field is missing from the final destination. I need guidance on how to indicate to the CSV parser what work type to use...or I need to understand if CSV can only import into Generic Works. Please let me know.
- Both tests have metadata in the date and date.other columns, because we want to leverage multiple date sorting functions on Hyku. The date.other data did not map to date created, although it should have based on the mapping spreadsheet.

**Comment by AKFosterDev** [comment]
Closing ticket: addressed in https://github.com/scientist-softserv/adventist-dl/issues/228
