### ISSUE TITLE
Spike: Highlighted full text search works snippets

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#163]
At present the [NewspaperWorks gem](https://github.com/samvera-labs/newspaper_works) provides the logic for rendering highlighted text.  This is not part of the current implementation; but is something we’re looking at incorporating, however that requires understanding the interaction with Abbyy and some additional work that we’ve done for other clients.

With that preliminary introduction, these are the things to consider:

-   [ ] *Amend the SOLR query* parameter logic to rquest highlighted text.
-   [ ] *Add the file set text* to the work’s SOLR document.
-   [ ] *Adjust the index field configuration* to render highlighted snippets
-   [ ] *Implement the snippet rendering* as a helper method
-   [ ] *Adjust UI styling* to handle multiple snippets per work (e.g. more than one place in the work matches the search term)

For *Amend the SOLR query* we have the following implementation in the Newspaper gem: <https://github.com/samvera-labs/newspaper_works/blob/bbe8736b0cf622d9c2577faf7a6f0a4e8dd1452c/app/search_builders/concerns/newspaper_works/highlight_search_params.rb#L1-L14>

For *Add the file set text* we have the following:  <https://github.com/samvera-labs/newspaper_works/blob/bbe8736b0cf622d9c2577faf7a6f0a4e8dd1452c/app/indexers/concerns/newspaper_works/indexes_full_text.rb#L4-L15>

One thing to consider is that the file\_set has

For *Adjust the index field configuration* we have the following implementation in another Hyku implementation: <https://github.com/scientist-softserv/louisville-hyku/blob/42a0fc837fd9ef4832a9741731672200e0097305/app/controllers/catalog_controller.rb#L147>

For *Implement the snippet rendering* look to the following: <https://github.com/samvera-labs/newspaper_works/blob/bbe8736b0cf622d9c2577faf7a6f0a4e8dd1452c/app/helpers/newspaper_works/newspaper_works_helper_behavior.rb#L83-L100>

For *Adjust UI styling* this is likely dependent on the specific CSS and markup of the current site.

**Note:** <https://github.com/scientist-softserv/nnp/blob/b5f7824bcc48a42f9b7ea8bdc0361b51ef26219c/app/indexers/fixed_price_list_indexer.rb#L19-L20> may contain additional guidance.

# Acceptance Criteria

- [x] Determine if we can render snippets, while also excluding child works from the search results - if yes, create follow up tickets

ref: #414

**Comment by jeremyf** [comment]
Prior art:

NNP has an index field `config.add_index_field 'all_text_tsimv', highlight: true, helper_method: :render_ocr_snippets`. The `render_ocr_snippets` is a method from newspaper_works gem.  However, the `all_text` field is NOT on the document.  There is work for adding the field to the document: see https://gitlab.com/notch8/newman-numismatic-portal/blob/c8c9a47e27be55d95c187ada65cdeffd58e143b4/app/indexers/fixed_price_list_indexer.rb#L20

**Comment by jeremyf** [comment]
In the [Samvera Newspaper Gem](https://github.com/samvera-labs/newspaper_works), there is a [partial for a work](https://github.com/samvera-labs/newspaper_works/blob/bbe8736b0cf622d9c2577faf7a6f0a4e8dd1452c/app/views/catalog/_thumbnail_list_newspaper_article.html.erb#L1-L6) that is there for text snippets:

```web
<div class="col-md-2">
  <div class="list-thumbnail" data-fileset="<%= document.file_set_ids&.first %>" data-query="<%= highlight_matches(document, 'all_text_tsimv', 'em') || search_query(current_search_session.query_params) %>">
    <%= render_newspaper_thumbnail_tag(document,
                                       current_search_session.query_params) %>
  </div>
</div>
```

Within the newspaper gem there are several renders that leverage the `highlight_matches` function.

**Comment by ShanaLMoore** [comment]
@jeremyf how would this work when we return parents only?

**Comment by ShanaLMoore** [comment]
the client may have to choose to return all works in catalog search, to support this feature.

**Comment by KatharineV** [comment]
If it is possible to deliver this feature while still excluding child works from the catalog search, then we would like this to be high priority in our next development sprint. If child works have to show in the catalog, then this is a no-go, as we have far too many child works and they don't make sense out of context.

**Comment by kirkkwang** [comment]
This ask _seems_ possible, but won't really know until I dig in and try it.  Looks like we would need to index the `all_text_tsimv` of all the file sets onto the parent work.  That means if a work has 10 pages.  Then it has to have all 10 pages of text indexed onto the work.

I asked Lea Ann because she did some work in NNP.  Here are some GitLab links for reference (no public view unfortunately, needs Rob's log in).

https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/84/diffs
[2:33](https://assaydepot.slack.com/archives/D0391GNQQAG/p1684445617245279)
https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/93
[2:34](https://assaydepot.slack.com/archives/D0391GNQQAG/p1684445698501989)
https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/181/diffs
[2:35](https://assaydepot.slack.com/archives/D0391GNQQAG/p1684445753254419)
https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/197/diffs
[2:36](https://assaydepot.slack.com/archives/D0391GNQQAG/p1684445816261969)
https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/261/diffs
