### ISSUE TITLE
Import question for adl:book set:

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#200]
# Summary 

> In an [import](https://adl.b2.adventistdigitallibrary.org/importers/30/entries/25449?locale%3Den&sa=D&source=editors&ust=1671480230566650&usg=AOvVaw38XmHGSazPOLL1K-0DcGtD) from 12/13/22 for 1,000 entries, 238 entries are enqueued and stuck processing. Any insight regarding the cause?

From https://docs.google.com/document/d/1mIOT23UAilSO77pAlXYSWJEHw3YK3BNNQVTKNzd41ao/edit#

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by jillpe** [comment]
related to #271

**Comment by KatharineV** [comment]
To test this ticket, I [replicated the importer](https://adl.s2.adventistdigitallibrary.org/importers/72?locale=en) that initially caused problems. I set the importer to bring in adl:book one time with a limit of 1,000. 

The importer is generating error messages. In my Hyku notifications, I see "File Import Errors." In the importer itself, I see works that failed to import due to RSolr::Error::ConnectionRefused. So far we have 35 entries processed, 11 failed, and 956 queued. Screenshots of error messages are below. 



![Image](https://user-images.githubusercontent.com/118196520/224788385-ce1362f7-d42e-4d07-a4ff-1f2320001c3c.png)



![Image](https://user-images.githubusercontent.com/118196520/224788191-a96a4194-5d6e-4c2b-aee3-ca3fa0856647.png)
