### ISSUE TITLE
Title of Metadata fields displaying on search page displaying inaccurately

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#227]
# Summary
In client meeting 1-17, Katharine confirmed the metadata fields being displayed hit expectations, however the title's were showing inaccurately, as "translation missing". See [link](https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q= ) for reference. 

# Acceptance Criteria
- [ ] Title of metadata fields displayed on search page display like the 'Description' field

Before: 
![Image](https://user-images.githubusercontent.com/10081604/213237092-e4aa075a-976b-4d90-aa31-5a7af8c5d5cf.png)

# Testing Instructions
- [ ] Go to homepage
- [ ] Click search button on search bar
- [ ] The resulting entries should display correctly and should not display "translations missing"

After:
![image](https://user-images.githubusercontent.com/95306716/215586766-339557f7-11fa-4bf3-8867-8f3f0801864c.png)

# Notes

### Implementation suggestion: 

Find the view partial, and locate the mapping for the fields. It may look something like 
en.helpers.action.importer.new

In the above example, you should be able to trace the mapping to the en locale file. Missing translation means that the mapping doesn't exist for that file, so you'll need to add one. 

The last step is to run translations for the project, so that it can convert the newly added english mapping to all the languages the project supports. But you may run into a blocker on this part (and it's ok to create a separate ticket for this).

Our google account needed to do this doesn't have any money on it. [Crystal posted a Q to Rob in slack for how to resolve this.](https://assaydepot.slack.com/archives/C0313NK7ACC/p1673993618633639)

**Comment by ShanaLMoore** [comment]
## dev notes

We found the cause of the missing translation error, for the [adventist](https://github.com/scientist-softserv/adventist-dl/issues/227) search result page.
It’s because the field_names are the [solr names](https://github.com/scientist-softserv/adventist-dl/blob/1c00ebb66db41c6ce53f60d848ad8d10362d45c1/app/views/catalog/_index_list_default.html.erb#L10), and [dog_biscuits.yml](https://github.com/scientist-softserv/adventist-dl/blob/1c00ebb66db41c6ce53f60d848ad8d10362d45c1/config/locales/dog_biscuits.en.yml#L1-L99) keys are not.
ie: part_of_tesim vs [part_of](https://github.com/scientist-softserv/adventist-dl/blob/1c00ebb66db41c6ce53f60d848ad8d10362d45c1/config/locales/dog_biscuits.en.yml#L78)
I’m wondering if we should add the solr name equivalent to the yml and call it a day?
Or, is there’s a way to convert the solr name to not include the suffix? I hesitate there because there are many suffix possibilities.
We may be able to do the latter programmatically, by chopping off the suffix, if we identify the ones it wants.

**Comment by ShanaLMoore** [comment]
We also noticed that there may be a dog biscuits auto loading issue, which could be the ultimate problem. 

When we make a change to the catalog controller, the correct labels suddenly appear 🙃 

/_[tesimb]+$/

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://sdapi.s2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=

<details><summary>"translation missing" is no longer found on the search results page</summary>

![Index Catalog Adventist Digital Library 2023-01-31 at 12 08 31 PM](https://user-images.githubusercontent.com/29311858/215872565-a15def62-d7ca-4962-aac9-2ce4cb79481d.jpg)
</details>

**Comment by KatharineV** [comment]
I'm seeing the titles display properly across the board. Thanks!
