### ISSUE TITLE
Subject not splitting on ';' - OAI Parser

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#232]
# Summary
The subjects for these periodical collections are appearing on Hyku as a single link. They aren't breaking at the semi-colon as expected. [Example](https://adl.s2.adventistdigitallibrary.org/collections/cfb630bc-6cec-4e49-ad55-79b0eacfb1e9?locale=en). Is this an easy fix on the development side? Or should we use a different character to delineate a split? Like a pipe instead of a semi-colon?

https://assaydepot.slack.com/archives/C0313NJV9PE/p1674496263830939?thread_ts=1674485123.289389&cid=C0313NJV9PE

*Note: This can be tested using the OaiEntrySpec file in the repository.*

# Acceptance Criteria

- [ ] the subject property should be separate links

**Comment by jeremyf** [comment]
This duplicates #206; closing that one in favor of this one.

**Comment by ShanaLMoore** [comment]
# QA RESULTS:

**Comment by KatharineV** [comment]
Subjects are splitting on articles I just imported to staging. Looks good. Example [here](https://adl.s2.adventistdigitallibrary.org/concern/journal_articles/13128998__1_98_fingernails?locale=en).

**Comment by KatharineV** [comment]
Looks good on staging as of 2023-03-07. I'm moving this ticket to the next column, because as far as I can see with the current testing instructions ([import ](https://adl.s2.adventistdigitallibrary.org/importers/66?locale=en#collection-entries)adl:periodical, check collection metadata, confirm and approve?), this is done.
