### ISSUE TITLE
Do not generate TIFF derivatives for IIIF Print

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#293]

**Comment by laritakr** [comment]
I am trying to clarify the intent of this ticket. From what I was told, this ticket was to split PDFs into PNGs rather than TIFFs. 

However the wording of the title leads me to wonder if this was the intention. The full range of derivatives possible via IiifPrint include: PDF, JP2, TIFF, and text (xml, json, and txt). Do we really want all of these to be generated for every work type except `Image`?

When you split a PDF into PNG files, the IIIF Print derivatives will still create derivative the full range of derivatives from the original PDF and each PNG file for everything except `Image` work types, which were configured to do only the text derivatives. This means the PDFs and PNGs would both have TIFF derivatives. The images below illustrate the behavior.

### Screenshot Examples

This was a `Published Work` type work with the attached PDF splitting into `Published Work` PNGs. The dropdown shows the derivatives that were created through IIIF Print for the PDF. 
![Screenshot 2023-03-10 at 12 14 59 PM](https://user-images.githubusercontent.com/17851674/224380222-fc51be39-e98f-4758-85bd-f7ef5aaf93e3.png)

When viewing the PNGs which are attached to the child works, you can see that again all types of derivatives were generated.
![Screenshot 2023-03-10 at 12 15 12 PM](https://user-images.githubusercontent.com/17851674/224380271-dce9a538-a053-4e27-a881-ccf13c8a5a02.png)

This was an `Image` type work with the attached PDF splitting into `Image`  PNGs. The dropdown shows that only the text derivatives that were created through IIIF Print because of the limitation for work type `Image` to generate only text derivatives.
![Screenshot 2023-03-10 at 11 48 22 AM](https://user-images.githubusercontent.com/17851674/224377845-f0f154cc-5c1c-4478-bed2-aa900d16a8b5.png)

**Comment by laritakr** [comment]
### A clarifying note: 

The full range of derivatives possible via IiifPrint include: PDF, JP2, TIFF, and text (xml, json, and txt). These are configurable on a work type basis. 

[A previous ticket](https://github.com/scientist-softserv/adventist-dl/issues/294) removed all derivatives except text from `Image` work type.
After discussion with Jill, the decision was made to also remove TIFF derivatives from all work types via this ticket.

**Comment by laritakr** [comment]
**Testing:** 

- [ ] Create an Image type work. The fileset's dropdown actions should allow downloading as only json, thumbnail, text, xml, or original file type (shown as simply download).
- [ ] Create any other type of work. The fileset's dropdown actions should allow downloading as jp2, pdf, json, text, xml, thumbnail, or original file type (shown as simply download). 
- [ ] Create a work with an attached PDF. The work will contain the PDF fileset with download options  jp2, json, text, xml, thumbnail, or original file type (shown as simply download). It will also have attached child works. 
- [ ] Open one of the child works. The file type will be PNG, and the download options will be  jp2, pdf, json, text, xml, thumbnail, or original file type (shown as simply download)

**Additional details:**

- TIFF will not appear anywhere in the download options.
- Note that if the attached file is already PDF, the pdf option would not appear again.

**Comment by AKFosterDev** [comment]
SoftServ QA Findings

Sample jpg [Here](https://user-images.githubusercontent.com/39319859/224793620-5b32e6c4-c26b-4883-84d4-ec75b7c8383a.jpg)

Sample pdf [Here](https://github.com/scientist-softserv/adventist-dl/files/10960454/1993_092_192503.pdf)


[Image Work ](https://adl.s2.adventistdigitallibrary.org/concern/images/86e6afad-c3b6-4094-ab48-2d553af710e0?locale=en)
* Uploaded sample file (jpg) as a an image work
* Derivatives created are xml, thumbnail, txt, and json (see screenshots)
* txt file contained all the words (see screenshots)
* was able to search the words in the UV
<details>
<summary>Image Screenshots</summary>

![Image](https://user-images.githubusercontent.com/39319859/224818273-fb74e8da-5bf2-40a0-b6b2-33681ab02528.png)

![Image](https://user-images.githubusercontent.com/39319859/224818353-ee62bca5-c2eb-46a8-9fa1-edcda3addb5a.png)

![Image](https://user-images.githubusercontent.com/39319859/224818465-b0818450-370a-4ead-a484-9f2590dba1b2.png)

</details>

[Generic Work - jpg](https://adl.s2.adventistdigitallibrary.org/concern/generic_works/df19c4f1-4f28-4e7f-9877-8a4b81eef468?locale=en)
* Uploaded sample file (jpg) as a generic work
* Created 1 item: (see screenshot)
    1) Derivatives: txt, jp2, json, pdf, xml, tiff, thumbnail
* was able to search the words in the UV

<details>
<summary>Generic work Screenshots</summary>

![image](https://user-images.githubusercontent.com/39319859/224840310-f8c6acbe-9eb6-4df7-a000-b75cca995cd1.png)

![image](https://user-images.githubusercontent.com/39319859/224840495-0e12dde6-8080-485b-a593-1bcb0c7a874e.png)

</details>

[Generic Work - pdf](https://adl.s2.adventistdigitallibrary.org/concern/generic_works/75512385-3710-490c-9031-01767509b759?locale=en)
* Uploaded sample file (pdf) as a generic work
* Created 1 item: (see screenshot)
    1) Derivatives: txt, jp2, json, xml, thumbnail
* PDF split to two pages
* WORK DID NOT RENDER IN UV

<details>
<summary>Generic work PDF Screenshots</summary>
**NO UV**

![image](https://user-images.githubusercontent.com/39319859/224859008-fb072b85-90df-4199-ab6d-385a6dee6090.png)

![image](https://user-images.githubusercontent.com/39319859/224859388-9200a527-8e33-483a-8678-c03e08e8fcaa.png)
</details>

[Conference Item - pdf](https://adl.s2.adventistdigitallibrary.org/concern/conference_items/5f6f56c6-4e52-4ed0-b05d-15c235f176c8?locale=en)
* Used same pdf sample file and uploaded as a conference item
* Derivatives created (see screenshot): txt, jp2, json, xml, tiff, thumbnail
* WORK DID NOT RENDER IN UV

<details>
<summary>Conference Item Screenshots</summary>

![image](https://user-images.githubusercontent.com/39319859/224859818-aca0b2b7-8942-46c0-867a-0bc42c470a08.png)

![image](https://user-images.githubusercontent.com/39319859/224859895-0b5ae437-1bd9-4b61-8e4d-b3e74448c456.png)

</details>

**Comment by jillpe** [comment]
Update: 

[Generic Work - pdf](https://adl.s2.adventistdigitallibrary.org/concern/generic_works/75512385-3710-490c-9031-01767509b759?locale=en) and [Conference Item - pdf](https://adl.s2.adventistdigitallibrary.org/concern/conference_items/5f6f56c6-4e52-4ed0-b05d-15c235f176c8?locale=en) does render in UV. There were a lot of jobs queued up yesterday, that made it take longer to complete the PDF jobs

**Comment by KatharineV** [comment]
Question: are the derivatives listed in the action drop down being generated by iiif_print every time a work is uploaded, contributing to the time it takes for a new work to load? If so, we may need to remove all derivatives as download options. We'd like to speed up the processing time. While the full list of derivatives is theoretically useful, it isn't so useful that it's worth expending measurable effort to provide all the options. We'd like to restrict time-consuming effort to only create derivatives necessary to deliver items in the viewer. 

@jillpe maybe we could address this in our meeting today?

**Comment by jillpe** [comment]
@KatharineV yes i've added it to the agenda!

**Comment by KatharineV** [comment]
I tested this ticket on production because of the book import on staging. 

[Image ](https://adl.b2.adventistdigitallibrary.org/concern/images/874e5b7c-e4db-4c9a-aa43-861442a18ec4?locale=en)work: 
Download options include txt, json, thumbnail, and xml. 
The TXT file does not contain words that appear in the image. The OCR generated gibberish because it read the bricks in the photo as text, but it did not read the text as text. The words on the image are fairly clear, and I hoped they would OCR properly, because they are a good example of text embedded in a photograph. What behavior should I expect here? I'm not too concerned about OCR'ing image work types. If it's an easy fix, then ok, but if it requires significant time and expertise, then we have other higher priorities and this can slide.

![Image](https://user-images.githubusercontent.com/118196520/228314914-089dedb9-b86d-4d2d-a46e-404914a82a87.png)

[Generic ](https://adl.b2.adventistdigitallibrary.org/concern/generic_works/c30f3b8e-e74f-4566-8157-03bf45a85e09?locale=en)work: 
Download options only include original file type and thumbnail. I believe this may be appropriate behavior, based on our desire to reduce derivatives to reduce processing time. Keyword search for a single term works. Multiple words aren't found or highlighted correctly. See screenshots below with example search for a first name vs. full name, which is a pretty frequent use case for our collections. Should the search work with multiple keywords in the UV? 

First name works--I searched "james"


![Image](https://user-images.githubusercontent.com/118196520/228316363-29292f92-5d38-43da-80e5-1882b2b5bc8e.png)


Full name does not work--I searched "james white" and got results of those two terms separately, but not together, even when they appear next to each other on the same page


![Image](https://user-images.githubusercontent.com/118196520/228316638-90287a15-a7a5-4e00-b0c6-d46c5deb903c.png)

Full name in quotation marks does not force results to show the terms together either. The search bar just spins and returns no results.


![Image](https://user-images.githubusercontent.com/118196520/228317248-a133c977-fe9a-4011-a43e-ce5c63a5315f.png)

Opening one of the [child works](https://adl.b2.adventistdigitallibrary.org/concern/parent/c30f3b8e-e74f-4566-8157-03bf45a85e09/generic_works/e88e4de1-75bb-48e7-b9cc-597ee22994bf), I see original file type, xml, thumbnail, txt, and json download options. Keyword search in the UV works. 

I also tested the other work types. Thesis, dataset, published work, exam paper, conference item, and journal article all accepted a single-page PDF, but no derivatives are present. The UV isn't showing on these work types with the PDF I uploaded. Is there something wrong with the PDF I chose? 

Additionally, the journal article work type did something VERY weird. I didn't put Location information into the metadata field, but the front end view of the item is showing #<Hyrax::ControlledVocabularies::Location:0x00007f8f341cab90>. I created this work through the UI, gave it a title and a copyright statement, added the PDF, and saved. Is this a bug? 

PDF and JPEG files I used for most examples are below.

[ADL Storage Plan V. 4.pdf](https://github.com/scientist-softserv/adventist-dl/files/11092341/ADL.Storage.Plan.V.4.pdf)


![Image](https://user-images.githubusercontent.com/118196520/228314397-016ded45-4b2d-4c25-86fc-70efbea986e6.jpg)

**Comment by KatharineV** [comment]
Tested this ticket on SDAPI staging and I have good results so far.

[Image ](https://sdapi.s2.adventistdigitallibrary.org/concern/images/19573665-6151-4eea-b02f-00f51cfc8798?locale=en)work type: Processing is very slow, so I'll circle back to edit with results when this image is done.

[Published ](https://sdapi.s2.adventistdigitallibrary.org/concern/theses/20121820_an_investigation_of_the_syntax_of_words_denoting_time_in_the_new_t?locale=en)Work work type: TIFF is not available in the action dropdown.

**Comment by laritakr** [comment]
The goal of the ticket is to no longer create tiff derivatives for the PDF. That means two things:

1. the PDF fileset dropdown doesn't have a tiff option
2. the child works from the PDF are now jpg rather than tiff

**Comment by KatharineV** [comment]
Testing against this [work ](https://sdapi.s2.adventistdigitallibrary.org/concern/published_works/22253132_spectrum_winter_1969?locale=en)on SDAPI staging, I see all working as expected, as Larita outlined in the updated expectations above.

**Comment by KatharineV** [comment]
Tested on production, and everything appears to be working as expected.
