### ISSUE TITLE
Spike: Some works import but don't bring in their associated file(s) from AWS

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#321]
# Story

Per Katharine, 

"Some works import but don't bring in their associated file(s) from AWS. [Here is an example](https://adl.s2.adventistdigitallibrary.org/concern/published_works/20214410_moral_and_religious_lessons_for_youth_and_children_numbers_16_20?locale=en) from the new book import where the PDF is missing and the file list includes a link rather than a PDF. Here is [a second example](https://adl.s2.adventistdigitallibrary.org/concern/published_works/20121631_a_sketch_of_the_christian_experience_and_views_of_ellen_g_white?locale=en) of the same problem and a [third](https://adl.s2.adventistdigitallibrary.org/concern/published_works/20121636_testimony_for_the_church_number_6?locale=en) example where only the thumbnail imported correctly. I've seen this issue off and on for the last couple months. It seems to be a new-ish problem."

# Acceptance Criteria

- [ ] TBD

# Screenshots / Video

<details>
<summary> Example 1: The PDF is missing and the file list includes a link rather than a PDF</summary>

![image](https://user-images.githubusercontent.com/10081604/226655544-bc57fe08-6996-49bb-b7f5-7fa6ea9d948e.png)

</details>

<details>
<summary> Example 2: Same problem as above </summary>

![image](https://user-images.githubusercontent.com/10081604/226656477-5ef30b53-f4ee-4138-97c1-1d2f43a81a48.png)

</details>

<details>
<summary> Example 3: only the thumbnail imported correctly</summary>

![image](https://user-images.githubusercontent.com/10081604/226656763-1902266e-d278-489b-b5e1-1d5402ed872d.png)

</details>

# Testing Instructions and Sample Files

Test with a variety of bulkrax imports to verify that problem is resolved (examples given and used for our testing were mcelhany.zip and spectrum.zip, each containing 5 works, and stored in the shared resources in SoftServe's google drive).

The new jobs dashboard is located at /jobs rather than /sidekiq and jobs can be monitored there. 

# Notes

This issue was reported when sidekiq jobs were still processing. Perhaps it could be a timing issue? re investigate once the jobs complete. 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/10081604/226655186-f19dc07f-9fc8-407d-8709-bb8aa925eb6f.png">

**Comment by ShanaLMoore** [comment]
@KatharineV How did this example get ingested? Do you have the imported file or params?

**Comment by jillpe** [comment]
Spike to triage the problems

**Comment by jillpe** [comment]
low high priority

**Comment by KatharineV** [comment]
@ShanaLMoore That example was imported with Bulkrax. This is not a critical pre-Board meeting priority, so you can bump it down the list as needed. I will look for a new example, since Staging was cleared. I've seen a couple on production, but they might resolve when Sidekiq says the processes are done. I'll circle back and let you know.

**Comment by laritakr** [comment]
Ref examples here: https://github.com/scientist-softserv/adventist-dl/issues/270#issue-1588346346

**Comment by laritakr** [comment]
Still blocked. Need import set causing issues.

**Comment by KatharineV** [comment]
Hi team, here are some examples with files that show "/concern/parent/AIN...etc" rather than file name in the Items list. Action dropdown says you can download. Trying to download results in an error (see screenshot).
These examples were imported via Bulkrax on Production.
![image](https://user-images.githubusercontent.com/118196520/230441515-b8087816-0a6c-42eb-af2c-fdcb7179a6c5.png)

[Example ](https://adl.b2.adventistdigitallibrary.org/concern/published_works/20088850_atlantic_union_gleaner_december_2_1903?locale=en)1
[Example ](https://adl.b2.adventistdigitallibrary.org/concern/published_works/20088821_atlantic_union_gleaner_may_13_1903?locale=en)2

**Comment by laritakr** [comment]
Duplicated locally with [backtrace saved here](https://docs.google.com/document/d/1Gu5SRS-NZ3niCHxRsR3qsCezvWnMMoDYV0MvFLCguLI/edit?usp=sharing)

**Comment by laritakr** [comment]
[Switching to GoodJobs ](https://github.com/scientist-softserv/adventist-dl/pull/360) and [prioritizing some jobs](https://github.com/scientist-softserv/adventist-dl/pull/373) was able to resolve many issues. This tends to indicate potential race conditions in jobs that may need further investigation. 

https://github.com/scientist-softserv/adventist-dl/issues/377 addresses one remaining point but does not appear to indicate a serious problem.

At this point, we need to monitor to see if issues continue.

**Comment by KatharineV** [comment]
I tested this ticket on SDAPI staging, and I created an importer for 10 works from the adl:book OAI set. I chose adl:book because that's the set where the file failures initially happened on ADL production. 

- importer: https://sdapi.s2.adventistdigitallibrary.org/importers/45?locale=en 

I checked all 10 works, and the files imported correctly, according to the work pages (see [example](https://sdapi.s2.adventistdigitallibrary.org/concern/published_works/20121626_testimony_for_the_church_number_3?locale=en)). Files can be downloaded from the Items list on a work page. File names show correctly. Everything seems fine, but I want to mention that as this importer ran, a series of alerts were generated on the notification page. The alerts said that files were failing to import. See screenshot below. Since the works are behaving as expected, perhaps the File Import Error notifications are unimportant? But since this ticket is explicitly about Bulkrax importing files, it seems relevant to at least mention that this 10 work importer generated 20 File Import Error notifications. 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/f1e03b83-0532-48bd-a8c2-404a6514065b)

**Comment by laritakr** [comment]
Yes you can ignore the file import errors. I found this [false error reporting bug](https://github.com/scientist-softserv/adventist-dl/issues/377) a month or so ago, but wasn't able to identify the cause of the false reporting. 

The place attempting to report the error was originally getting an error and swallowing the actual error that was being reported. That has been fixed, so it now shows the errors you are seeing rather than the error shown in the bug ticket I made.

**Comment by KatharineV** [comment]
I imported one work from the adl:book set to ADL production. All files appear as expected on the work page on Hyku. 

- Work: https://adl.s2.adventistdigitallibrary.org/concern/published_works/22253540_meeting_of_the_health_reform_institute?locale=en
- Importer: https://adl.s2.adventistdigitallibrary.org/importers/12?locale=en
