### ISSUE TITLE
SPIKE: Bulkrax issues on SDAPI tenant

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist-dl#382]
# Accepted Criteria
- [ ] Create new tickets after identifying actions that are needed to get imports working.

Bulkrax does not bring in every record in the OAI sets we try to import to the SDAPI tenant. 

I have run imports several times that should have pulled the complete SDAPI obituary or article sets, and the importers always stop before reaching the total number of works in the set. Every time I run an import, the total number of works in the database does increase, and the new works are clearly picked up from all different places in the OAI set. I can determine this because works in the sdapi:article set are alphabetical by article title. The most recent SDAPI article [importer ](https://sdapi.b2.adventistdigitallibrary.org/importers/17?locale=en)brought in new works with titles beginning with "F." But it is now stuck pending at 47,812 works out of 485,676 total, and Sidekiq is quiet. 

Additionally, some entries fail. To complete this migration, I need to bring the complete SDAPI OAI sets into Hyku without failures or skipped records. 

Can you help me truly load the SDAPI tenant once and for all, to bring the existing OAI sets into the database so I can know it is "complete" with old citations before I attempt bringing it up to date (with new citations created since Eric last harvested the database in September 2021)?

**Comment by ShanaLMoore** [comment]
Is this related to the memory leak issue UTK experienced? That has since been fixed in bulkrax if so.

**Comment by ShanaLMoore** [comment]
ref for helpful context: https://assaydepot.slack.com/archives/G0311DN2YCA/p1684246036915769

**Comment by ShanaLMoore** [comment]
cc @kirkkwang If I can't complete this today, I'm going to hand this one over to you since #402 is dependent on, and related to, it. 

Let me know if you have any questions. 

I'm not sure if I'll be able to see it get stuck before my PTO starts. If you end up seeing this behavior, I'd imagine Rob may be the POC for further guidance. 

We often would want to check the CPU of the containers. Will giving it more resource resolve this? 

Last time (UTK), we discovered bulkrax causes a memory leak in a loop. When this happened, the container would fill up and eventually crash it. Mark would have to run another import to essentially start over. If you go into staging's console, you should be able to see the pending relationships that didn't run though. You could nurse it along manually from there. 

Check out [this thread](https://assaydepot.slack.com/archives/G031E2P1RJM/p1676572533901659) for context. This issue has sense been resolve now though so hopefully this was what Katharine saw and it has since been fixed.

**Comment by ShanaLMoore** [comment]
@KatharineV was this issue in staging or prod? I assume prod?

**Comment by ShanaLMoore** [comment]
Comparing both env configs, [prod](https://github.com/scientist-softserv/adventist-dl/blob/main/ops/production-deploy.tmpl.yaml) and [staging](https://github.com/scientist-softserv/adventist-dl/blob/main/ops/dev-deploy.tmpl.yaml) look the same so it shouldn't be a diff there. But prod is waiting for an approval for deploy.

**Comment by KatharineV** [comment]
@ShanaLMoore Sorry I missed your comment yesterday. It looks like you don't need anything from me anymore on that question, but let me know if I'm wrong.
