### ISSUE TITLE
SDAPI: Adding works to collections

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#516]
Account administrators and users marked as "managers" of collections are unable to add any works to any collections. Based on user documentation about groups and roles, this behavior does not fit expectations. We expect:

- Account admins and managers to add existing works to collections where they have permissions
- Account admins and managers to add new works to collections where they have permissions

Currently, neither of those functions is working. We understand that some works were added to the tenant after the users received permissions, and those works would not be able to add, based on the rules in Hyku. However, the vanarsdk user has been an account admin for a long time and owns works in the repository. Using that account, I still cannot add works that belong to me to collections where I should theoretically have admin privilege (unless I am still misunderstanding how the roles and permissions should work). If we are misunderstanding permissions, then please focus on the second part of this ticket, concerning new works, because they are blocked from adding to collections and this is a critical issue for us. Thank you!

Example: 

![Image](https://user-images.githubusercontent.com/118196520/257818836-f72d6233-8c22-42d0-a13b-878ecc30a1c6.png)

These users are marked as [account admins](https://b2.adventistdigitallibrary.org/proprietor/accounts/1?locale=en). 

The content@adl and vanarsdk@andrews accounts are additionally added to this sample collection, [Adventist Review](https://sdapi.b2.adventistdigitallibrary.org/dashboard/collections/b9093de8-baa4-4e63-af66-647bb7cddbf9?locale=en), as Managers.

![Image](https://user-images.githubusercontent.com/118196520/257819164-6656ac9a-529c-491f-990a-4034f2f21a6e.png)

As you can see in these screenshots taken using the vanarsdk@andrews account, I cannot add an existing work or a new work to the Adventist Review collection. It does not appear in the "Add to collection" drop down.

Existing work that I tested: https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13759336_snow_samuel_sheffield 

![Image](https://user-images.githubusercontent.com/118196520/257820400-00622935-d84f-4274-9c78-01c9b303cdfd.png)

New test work: (please note that I cannot share a URL for this test work, because we cannot actually save a new work on SDAPI right now--we get a 504 Gateway Time-out.)

![Image](https://user-images.githubusercontent.com/118196520/257820863-19b64c73-c282-412d-bc00-966ba91952fe.png)

# Testing Instructions
Follow client-provided screenshots for guidance or
As an admin user, from the admin dashboard click collections and note the name of one. This is the collection you'll add a work to. 
Navigate to the works index page by clicking on works in the left sidebar. 
Click on the checkbox of a work you want to add to collection. An Add to Collection button should appear. Click it. A modal should appear...

# Acceptance Criteria
- [ ] a user should be able to start typing the name of the collection and have it appear. Save
- [ ] navigate back to the collection, the work should be there. The collection's item count should increment by the number of works you added.

**Comment by ShanaLMoore** [comment]
# Analysis

@KatharineV To unblock you, you can add to a collection in an alternate way. First you'd go to the collection from the admin dashboard and click "Add existing works to collections" 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/a9955811-df59-4e16-93b4-2cabe4a9e48e)

It will redirect you to the works index page, check one of the work's check boxes and it will auto populate the collection title in the drop down. 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/38fbd90c-ef2c-478f-82a9-3678e1d80ca2)

Click save changes and you will see the work got added to that collection. 

However I am observing the same problem with being able to type it in yourself and will look into that now. The problem seems to be with the type ahead functionality of the drop down and not that you can't add a work to the collection. 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/d07ffcfb-13cf-4b0f-a510-b71ef47880d6)

**Comment by jillpe** [comment]
SoftServ QA: PASS

[Collection Url](https://sdapi.s2.adventistdigitallibrary.org/dashboard/collections/e276dfd6-f041-45fc-854c-661b97495534?locale=en)

[Work Url](https://sdapi.s2.adventistdigitallibrary.org/concern/published_works/7a64aa6f-29e8-488b-aa0e-c42eb8a8686c?locale=en)

Add the above work to the above collection and it saved. See screenshot below
<details><summary>Screenshot</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/62f51fd7-b4c2-4230-9151-d5a15350048f)


</details>
