### ISSUE TITLE
styling looks off

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#562]
# Summary
Logo looks too big. 

Are the footer links in the correct position?

Theme is not implemented?

Are the styles not getting loaded?

# Testing Instructions

NOTE: Please ask a dev about compiling assets on staging before QA'ing this ticket

# Acceptance Criteria
The general look and feel should match adventist proper's [staging](https://sdapi.s2.adventistdigitallibrary.org/)

# Screenshots
![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/6c55e4b1-631e-4ea8-b6fe-9dea2e92c6f4)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/77082cac-e262-40b4-a954-befc1e1d6c32)

# STAGING

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/876ee5c4-52f1-46ee-8479-33f9a50f3fb6)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/1a2e6114-35dc-4b8c-8d55-09af83c6acb4)

**Comment by laritakr** [comment]
@jillpe should this be pulled back to rework the show pages, or should that be a new ticket?

**Comment by KatharineV** [comment]
Another piece of weird styling revealed itself today. A collection homepage is showing the title in white font on a white background with raised text shadows. Usually, Hyku only shows me this view if I try to upload a banner to a collection page (and I never do that because the feature breaks collections so they can't be edited). 

First screenshot below shows a Knapsack [collection ](https://demo.adventist-knapsack-staging.notch8.cloud/collections/f5ece824-25f5-4383-a432-255860e40750?locale=en)with weird homepage styling. Second screenshot shows the expected font look on a [collection ](https://adl.b2.adventistdigitallibrary.org/collections/0ed83a24-3553-48bf-8216-eca875cbc48b?locale=en)homepage with no banner image.


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/c7dca9be-1b19-4867-b93e-32ccc02a6aa8)


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/0dc7646c-4ee5-4830-9995-7080abfbcb7b)

**Comment by ShanaLMoore** [comment]
I'm going to make separate tickets for the additional issues.
