### ISSUE TITLE
☄️ Epic: Full Text Search - Highlighted

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#73]
# Summary
Adventist wants full-text search with highlighted search terms in the viewer.
When a user searches for a keyword or phrase, they want the application to return search results in a regular search results format, but include works that contain that keyword or phrase. 

They would also like for the viewer to automatically show the first instance of the search term when a user clicks on the search result and the work page loads. 

They would like to use PDFtron and UV as the viewer.

**Past projects that may be helpful:**

NNP 
- Two step process - search text to get search results, then search in UV on that object to find that area.  Rob: Have to OCR documents w/ coordinates (this is CPU-consuming)

[UCLA Oral Histories uses this](https://oralhistory.library.ucla.edu/)

# Acceptance Criteria

- [x] #163
- [x] #414 
- [x] #96
~~[Imported txt files are re-indexed so the data is available](https://gitlab.com/notch8/adventist-dl/-/issues/147)~~
~~[PDFtron is searchable](https://gitlab.com/notch8/adventist-dl/-/issues/150)~~

# Screenshots or Video

# Testing Instructions

# Notes
- Does this ticket need to be broken down into two tickets?
- How many characters do we want the results of the search terms display?

**Comment by KatharineV** [comment]
In testing on production today I am getting results with keywords found in full text, but I am no longer getting results with keywords found in metadata fields. For example, a search for "lake region" will not return this image https://adl.b2.adventistdigitallibrary.org/concern/images/p_000456_lake_region_junior_camp?locale=en which has those words in the title. In fact, I can't get images to return in search results, except for one wild example just now. I searched for ARK ID 22252242 which matches https://adl.b2.adventistdigitallibrary.org/concern/published_works/22252242__the_gist_of_christian_education?locale=en. The search results don't bring up that published work. Instead, I get an image where I don't see my search term and I don't understand why the image came up. Here's [my search UR](https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=22252242)L and the [image ](https://adl.b2.adventistdigitallibrary.org/concern/images/20119170_ellen_g_white_and_her_twin_sister_elizabeth_m_bangs?locale=en)that came up.

**Comment by jillpe** [comment]
Confirmed 2023-01-31 we will be moving forward with Tesseract Best for OCR

**Comment by KatharineV** [comment]
Implementing all the features of this full text search highlighting will be high priority in our next development sprint.

**Comment by KatharineV** [comment]
In my testing on ADL staging, I see all features except one are present and working. I do not see persistent highlighting of a search term from the snippets to the UV in a selected work. Based on some comments above on this ticket and on ticket #96, I thought I might see that feature. Since there are no testing instructions for this ticket, can you clarify for me if the highlighting should be persistent based on the work done so far? Or should I expect to see that feature on a different ticket later? Thanks.

**Comment by KatharineV** [comment]
Thank you Jill and Shayna for answering my question above. Everything is working as expected except for the persistent highlighting. Since the persistent highlighting was lost due to a bug, I know a new ticket will pop up for that. So, I'll move this particular epic along the boards, because the initial work it represents is done and successful.
