### ISSUE TITLE
Search in the UV not working

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#751]
After Knapsack, the search box in the UV is not working. The example document below contains the word "work" multiple times, so I assume that Tesseract caught at least one of those instances. The word "work" should be searchable. When I enter the word in the search box and hit enter, I get a spinning circle that never resolves. The word never highlights and I don't get an error message or anything. 

https://adl.b2.adventistdigitallibrary.org/concern/generic_works/wdf_0010_005_the_nashville_sanitarium_ellen_g_white_extracts_from_lette?locale=en
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/43bd11ab-e74e-41c6-8267-fdf54e4b5c7f)

**Comment by ShanaLMoore** [comment]
This wasn't working due to mixed content error seen in the console. Once I marked the tenant as ssl_configured: true, the search works again - 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/71dfc1e4-9e3c-48ba-b4d8-4220ebe9d1e9)




![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/33d4d876-e75c-4df8-9109-d0b6795abc81)

Please give it a go and let us know if there's still a problem.

**Comment by KatharineV** [comment]
I tested on ADL prod, and the UV search worked. Yay! 

But the UV search is still not working in staging.
https://testing.s2.adventistdigitallibrary.org/concern/published_works/019887_an_explanation_of_the_new_folding_prophetic_chart
It just spins and never finds the term, although I can see the word on the page. 


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/15f6cc0b-3aa0-40cb-b66e-a9b848cc91dc)

**Comment by ShanaLMoore** [comment]
@KatharineV This is resolved by setting the ssl_configured to true for the tenant

ref: 
- https://testing.s2.adventistdigitallibrary.org/concern/published_works/019887_an_explanation_of_the_new_folding_prophetic_chart

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/70bde82c-d677-4038-97f2-59b537c7655c)




![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/034ca63b-4d0f-49e4-a831-550f19e55e88)

**Comment by KatharineV** [comment]
Thanks, @ShanaLMoore . Is the Ssl feature one that I need to flip on for all our tenants? If so, can you tell me which part of the dashboard is showing in that screenshot above? I can go through all the tenants and make sure it's on.

**Comment by ShanaLMoore** [comment]
We were just talking about if we should consider turning ssl_configured on by default for everyone since it definitely seems to be the way you'd need it. 

You go to admin dashboard. In the left column click Settings > Account. Scroll all the way down and check the checkbox for ssl_configured. Click Save Changes. 

demo: https://share.zight.com/RBuAKXd2

**Comment by KatharineV** [comment]
Thanks! I've set Ssl configured to True for all the (in-use) tenants in B2 and S2.
